# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

#target 'TestFireStoreQuery_1' do
#  # Comment the next line if you don't want to use dynamic frameworks
#  use_frameworks!
#
#  # Pods for TestFireStoreQuery_1
#
#  target 'TestFireStoreQuery_1Tests' do
#    inherit! :search_paths
#    # Pods for testing
#  end
#
#  target 'TestFireStoreQuery_1UITests' do
#    # Pods for testing
#  end
#
#end

target 'TestFireStoreQuery_1' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for firestoreapp
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firestore', :podspec => 'https://storage.googleapis.com/firebase-preview-drop/ios/firestore/0.7.0/Firestore.podspec.json'
end
