# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Line_Chart_Test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Line_Chart_Test
  pod 'Charts'
  pod 'TinyConstraints'

  target 'Line_Chart_TestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Line_Chart_TestUITests' do
    # Pods for testing
  end

end
