# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Burlington Water Quality Dashboard' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Burlington Water Quality Dashboard
  # Pods for firestoreapp
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firestore', :podspec => 'https://storage.googleapis.com/firebase-preview-drop/ios/firestore/0.7.0/Firestore.podspec.json'
  pod 'Charts'
  pod 'TinyConstraints'
  pod 'SimpleCheckbox'
end